// This file is automatically generated. Do not modify it manually.
// This file is used to initialize the Firebase app.

export const firebaseConfig = {
  apiKey: "AIzaSyClUx-ElLCSfzy5B8GOIff9uaRo_bdXIWo",
  authDomain: "studio-7290981178-5eeb4.firebaseapp.com",
  projectId: "studio-7290981178-5eeb4",
  storageBucket: "studio-7290981178-5eeb4.appspot.com",
  messagingSenderId: "967094846199",
  appId: "1:967094846199:web:ecd52b0b7237b2e66589f2",
  measurementId: "G-J502S6L5T9"
};
